import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo,
  Suspense,
  lazy,
  Component,
  memo,
  type ReactNode,
  type ReactElement,
  type FC,
  type ComponentType,
  type ErrorInfo,
  type PropsWithChildren,
  type ChangeEvent,
  type FormEvent,
  type SetStateAction,
  type RefAttributes,
  type JSXElementConstructor,
} from "react";

export {
  createContext,
  useContext,
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo,
  Suspense,
  lazy,
  Component,
  memo,
  type ReactNode,
  type ReactElement,
  type FC,
  type ComponentType,
  type ErrorInfo,
  type PropsWithChildren,
  type ChangeEvent,
  type FormEvent,
  type SetStateAction,
  type RefAttributes,
  type JSXElementConstructor,
};

export default React;
